// tests/MANIFEST.md, the one overview of every Vitest file (the GD lock on #191, #229): each slice
// with its files and test counts, the kernel by area, and the cross-slice checks. Tests are what
// `vitest list` collects; sites count the `it`/`test` calls in a file's source, so the drift check
// can tell a test added without regenerating from the source alone, without starting Vitest.
// Pure: writeTestManifest.mjs does the listing and the file system.
import { featureOfTestFile } from '../ci/testFeatures.mjs'

export const MANIFEST_PATH = 'tests/MANIFEST.md'
export const MANIFEST_COMMAND = 'npm run tests:manifest'

const SLICE_FOLDER = /^src\/features\/([^/]+)\//
const FILE_ROW = /^\| `([^`]+)` \| (\d+) \| (\d+) \|$/
// One call per line with any modifier chain: it(, test.todo(, it.each([...])(, it.skipIf(x)(.
const TEST_SITE = /^\s*(?:it|test)(?:\.\w+(?:\([^)]*\))?)*\s*[(`]/gm
const FILE_TABLE_HEAD = ['| File | Tests | Sites |', '| --- | --- | --- |']
const NONE = '-'

/** The slice a test file belongs to, or null for a kernel or script test. */
export function sliceOfTestFile(path) {
  return SLICE_FOLDER.exec(path)?.[1] ?? null
}

export function countTestSites(source) {
  return source.match(TEST_SITE)?.length ?? 0
}

/** The file rows of a manifest by path: `{ path, tests, sites }`. */
export function readManifestFiles(markdown) {
  const rows = markdown.split('\n').flatMap((line) => fileRowOf(line))
  return new Map(rows.map((row) => [row.path, row]))
}

function fileRowOf(line) {
  const match = FILE_ROW.exec(line)
  if (match === null) return []
  return [{ path: match[1], tests: Number(match[2]), sites: Number(match[3]) }]
}

/** Paths of files on disk that are new to the manifest or whose test sites changed. */
export function staleTestPaths(diskFiles, manifestFiles) {
  return diskFiles
    .filter(({ path, sites }) => manifestFiles.get(path)?.sites !== sites)
    .map(({ path }) => path)
}

/**
 * The rows for the files on disk: a refreshed file takes its listed count (0 when `vitest list`
 * collected nothing, such as a file whose only test is skipped), the rest keep their row.
 */
export function refreshManifestFiles({ diskFiles, manifestFiles, listedCounts, refreshedPaths }) {
  return diskFiles.map(({ path, sites }) => ({
    path,
    sites,
    tests: refreshedPaths.has(path)
      ? (listedCounts.get(path) ?? 0)
      : (manifestFiles.get(path)?.tests ?? 0),
  }))
}

/** Tests per file from `vitest list --json` entries (`{ name, file }`, absolute paths). */
export function countListedTests(entries, root) {
  const counts = new Map()
  const prefix = `${root.replaceAll('\\', '/')}/`
  entries.forEach(({ file }) => {
    const path = file.replaceAll('\\', '/').replace(prefix, '')
    counts.set(path, (counts.get(path) ?? 0) + 1)
  })
  return counts
}

/** The whole manifest; rows sorted by path in code-unit order so every machine writes the same. */
export function renderTestManifest(files, checks, seeds) {
  const sorted = [...files].sort(compareByPath)
  return [
    ...introLines(),
    ...crossSliceLines(checks, seeds, sorted),
    ...sliceLines(sorted),
    ...kernelLines(sorted),
  ].join('\n')
}

function compareByPath(a, b) {
  if (a.path === b.path) return 0
  return a.path < b.path ? -1 : 1
}

function introLines() {
  return [
    '# Test manifest',
    '',
    `<!-- Generated by \`${MANIFEST_COMMAND}\` (scripts/tests); never edit by hand. -->`,
    '',
    'Every Vitest file by feature slice and kernel area, and the kernel-owned checks across slices',
    '(the GD lock on #191). **Tests** is what `vitest list` collects; **Sites** counts the `it` and',
    '`test` calls in the source, which `scripts/tests/manifestDrift.test.mjs` compares on every box',
    'Tester run, so a test added, moved or deleted without regenerating fails there. After changing',
    `tests run \`${MANIFEST_COMMAND}\`: it lists only the new and changed files (add test files as`,
    'arguments to refresh them too, or `-- --all` for the whole suite, which takes minutes).',
    '',
    'There is no grand total, so two branches adding tests do not conflict on one line.',
    '',
  ]
}

function crossSliceLines(checks, seeds, files) {
  const testsByPath = new Map(files.map((file) => [file.path, file.tests]))
  return [
    '## Cross-slice checks',
    '',
    `Gate seeds: ${seeds.join(', ')} (\`src/constants/pacingSeeds.ts\`, #84).`,
    '',
    '| Check | Decided in | Where | Tests |',
    '| --- | --- | --- | --- |',
    ...checks.map((check) => crossSliceRow(check, testsByPath)),
    '',
  ]
}

function crossSliceRow(check, testsByPath) {
  const where = [...check.files, ...check.commands].map((item) => `\`${item}\``)
  if (check.pending !== null) where.push(check.pending)
  return `| ${check.check} | ${check.decidedIn} | ${where.join(', ')} | ${checkTestCount(check, testsByPath)} |`
}

function checkTestCount(check, testsByPath) {
  if (check.files.length === 0) return NONE
  return check.files.reduce((sum, path) => sum + (testsByPath.get(path) ?? 0), 0)
}

function sliceLines(files) {
  const bySlice = groupFiles(files, sliceOfTestFile)
  return ['## Slices', '', ...[...bySlice].flatMap(([slice, rows]) => sliceGroupLines(slice, rows))]
}

function sliceGroupLines(slice, rows) {
  const tests = rows.reduce((sum, row) => sum + row.tests, 0)
  const heading = `### \`${slice}\`: ${rows.length} ${plural(rows.length, 'file')}, ${tests} ${plural(tests, 'test')}`
  return [heading, '', ...fileTableLines(rows)]
}

// Kernel groups carry no totals: two branches adding tests to one area would conflict on them.
function kernelLines(files) {
  const kernelFiles = files.filter((file) => sliceOfTestFile(file.path) === null)
  const byArea = groupFiles(kernelFiles, featureOfTestFile)
  return [
    '## Kernel',
    '',
    ...[...byArea].flatMap(([area, rows]) => [`### \`${area}\``, '', ...fileTableLines(rows)]),
  ]
}

/** Files grouped by a key, keys sorted; files the key maps to null are left out. */
function groupFiles(files, keyOf) {
  const groups = new Map()
  files.forEach((file) => {
    const key = keyOf(file.path)
    if (key !== null) groups.set(key, [...(groups.get(key) ?? []), file])
  })
  return new Map([...groups].sort(([a], [b]) => (a < b ? -1 : 1)))
}

function fileTableLines(rows) {
  return [...FILE_TABLE_HEAD, ...rows.map(fileRowLine), '']
}

function fileRowLine({ path, tests, sites }) {
  return `| \`${path}\` | ${tests} | ${sites} |`
}

function plural(count, noun) {
  return count === 1 ? noun : `${noun}s`
}
