/**
 * Every `data-testid` the HUD, the bay screens and settings overlay carry (#33 sections 5, 6
 * and 9, #37 `sellbay-*` and `upgradebay-*`, #105 `refinerybay-*`), in one table: the view models name their buttons with it and the components take their ids
 * from it (re-exported as `UI_IDS` from `src/ui/ids.ts`), so a spec, the debug API and the DOM
 * always agree. Rows that repeat take their id from a template.
 */
import type { UpgradeId } from '../economy/economyDefinition'

export const UI_IDS = {
  hudEnergyGauge: 'hud-energy-gauge',
  hudEnergyText: 'hud-energy-text',
  hudHullGauge: 'hud-hull-gauge',
  hudHullText: 'hud-hull-text',
  hudCargoGauge: 'hud-cargo-gauge',
  hudCargoText: 'hud-cargo-text',
  hudCargoCore: 'hud-cargo-core',
  hudCargoFull: 'hud-cargo-full',
  hudCargoValue: 'hud-cargo-value',
  hudLiningBill: 'hud-lining-bill',
  hudDepth: 'hud-depth',
  hudBand: 'hud-band',
  hudCasing: 'hud-casing',
  hudGuns: 'hud-guns',
  hudGunsIdle: 'hud-guns-idle',
  hudCharges: 'hud-charges',
  hudChargeFuse: 'hud-charge-fuse',
  hudHeatGauge: 'hud-heat-gauge',
  hudHeatText: 'hud-heat-text',
  hudHeatThrottled: 'hud-heat-throttled',
  hudCompassDock: 'hud-compass-dock',
  hudCoreDistance: 'hud-core-distance',
  hudTileTime: 'hud-tile-time',
  hudState: 'hud-state',
  hudRescueCountdown: 'hud-rescue-countdown',
  hudDockPrompt: 'hud-dock-prompt',
  hudCachePrompt: 'hud-cache-prompt',
  hudDebugMark: 'hud-debug-mark',
  hudWarningEnergy: 'hud-warning-energy',
  hudHintPlaque: 'hud-hint-plaque',
  hudTransmission: 'hud-transmission',
  platformScreen: 'platform-screen',
  sellbayScreen: 'sellbay-screen',
  upgradebayScreen: 'upgradebay-screen',
  upgradebayPreview: 'upgradebay-preview',
  upgradebayCasing: 'upgradebay-casing',
  upgradebayCasingGrade: 'upgradebay-casing-grade',
  upgradebayCasingCost: 'upgradebay-casing-cost',
  upgradebayCasingBuy: 'upgradebay-casing-buy',
  upgradebayGuns: 'upgradebay-guns',
  upgradebayGunsLevel: 'upgradebay-guns-level',
  upgradebayGunsCost: 'upgradebay-guns-cost',
  upgradebayGunsEffect: 'upgradebay-guns-effect',
  upgradebayGunsBuy: 'upgradebay-guns-buy',
  upgradebayCharges: 'upgradebay-charges',
  upgradebayChargesCarried: 'upgradebay-charges-carried',
  upgradebayChargesCost: 'upgradebay-charges-cost',
  upgradebayChargesEffect: 'upgradebay-charges-effect',
  upgradebayChargesRestock: 'upgradebay-charges-restock',
  upgradebayRack: 'upgradebay-rack',
  upgradebayRackSize: 'upgradebay-rack-size',
  upgradebayRackCost: 'upgradebay-rack-cost',
  upgradebayRackEffect: 'upgradebay-rack-effect',
  upgradebayRackBuy: 'upgradebay-rack-buy',
  upgradebayLining: 'upgradebay-lining',
  upgradebayLiningActive: 'upgradebay-lining-active',
  upgradebayLiningCost: 'upgradebay-lining-cost',
  upgradebayLiningEffect: 'upgradebay-lining-effect',
  upgradebayLiningButton: 'upgradebay-lining-button',
  upgradebayQuickService: 'upgradebay-quick-service',
  refinerybayScreen: 'refinerybay-screen',
  refinerybayBatchCap: 'refinerybay-batch-cap',
  refinerybaySlotBuy: 'refinerybay-slot-buy',
  refinerybaySlotPrice: 'refinerybay-slot-price',
  sellbayRefined: 'sellbay-refined',
  sellbayRefinedTotal: 'sellbay-refined-total',
  sellbayRefinedCollect: 'sellbay-refined-collect',
  sellbayLining: 'sellbay-lining',
  sellbayLiningBilled: 'sellbay-lining-billed',
  sellbayLiningPaid: 'sellbay-lining-paid',
  sellbayLiningForgiven: 'sellbay-lining-forgiven',
  platformMoney: 'platform-money',
  platformPlanet: 'platform-planet',
  platformCoreBay: 'platform-core-bay',
  platformCoreBayGauge: 'platform-core-bay-gauge',
  platformState: 'platform-state',
  shopCargoTotal: 'shop-cargo-total',
  shopSellAll: 'shop-sell-all',
  shopSellAllValue: 'shop-sell-all-value',
  workshopHull: 'workshop-hull',
  workshopRepair: 'workshop-repair',
  workshopRepairCost: 'workshop-repair-cost',
  workshopVisualTier: 'workshop-visual-tier',
  chargingEnergy: 'charging-energy',
  chargingPrice: 'charging-price',
  chargingCost: 'charging-cost',
  chargingRecharge: 'charging-recharge',
  platformQuickService: 'platform-quick-service',
  platformQuickTotal: 'platform-quick-total',
  platformTravel: 'platform-travel',
  platformTravelFee: 'platform-travel-fee',
  platformTravelFragments: 'platform-travel-fragments',
  platformTravelConfirm: 'platform-travel-confirm',
  platformEndCard: 'platform-end-card',
  platformUndock: 'platform-undock',
  platformSettings: 'platform-settings',
  artefactChoice: 'artefact-choice',
  artefactLeave: 'artefact-leave',
  settingsPanel: 'settings-panel',
  settingsBindingProblems: 'settings-binding-problems',
  settingsResetBindings: 'settings-reset-bindings',
  settingsClose: 'settings-close',
} as const

export type UiId = (typeof UI_IDS)[keyof typeof UI_IDS]

/** Ids of repeated rows: one per threat, ore tier, upgrade track, setting and action. */
export const UI_ID_TEMPLATES = {
  hudThreat: (index: number) => `hud-threat-${index}`,
  shopRow: (tier: number) => `shop-row-${tier}`,
  shopSell: (tier: number) => `shop-sell-${tier}`,
  refinerybayOre: (tier: number) => `refinerybay-ore-${tier}`,
  refinerybayQueue: (tier: number) => `refinerybay-queue-${tier}`,
  refinerybaySlot: (index: number) => `refinerybay-slot-${index}`,
  sellbayRefinedLine: (slot: number) => `sellbay-refined-line-${slot}`,
  workshopUpgrade: (upgradeId: UpgradeId) => `workshop-upgrade-${upgradeId}`,
  workshopUpgradeLevel: (upgradeId: UpgradeId) => `workshop-upgrade-${upgradeId}-level`,
  workshopUpgradeCost: (upgradeId: UpgradeId) => `workshop-upgrade-${upgradeId}-cost`,
  workshopUpgradeEffectBefore: (upgradeId: UpgradeId) =>
    `workshop-upgrade-${upgradeId}-effect-before`,
  workshopUpgradeEffectAfter: (upgradeId: UpgradeId) =>
    `workshop-upgrade-${upgradeId}-effect-after`,
  workshopUpgradeBuy: (upgradeId: UpgradeId) => `workshop-upgrade-${upgradeId}-buy`,
  artefactCard: (optionId: string) => `artefact-card-${optionId}`,
  artefactChoose: (optionId: string) => `artefact-choose-${optionId}`,
  settingsToggle: (name: string) => `settings-toggle-${name}`,
  settingsRebind: (actionId: string) => `settings-rebind-${actionId}`,
} as const
